### ISSUE TITLE
Update to angular 18?

### ISSUE THREAD

**Issue by jonschmidt** [luukhaijes/kinde-angular#17]
**Is your feature request related to a problem? Please describe.**
Can we update this library to angular 18? It has been out for 2 months now, and I would love to start building with this library, but we cannot until it is updated

**Describe the solution you'd like**
Update to angular 18

**Comment by JoshuaNitschke** [comment]
I am using it with an angular 18 app, no issues yet.  I switched from angular-auth-oidc-client and custom auth guard to this wrapper with the  built in auth guard.  Works great.

**Comment by jonschmidt** [comment]
Ah, good to know. Are you using `--force` or `--legacy-peer-deps`? 

I could not get past a typescript error in the libraries angular dependency, but I will keep trying

**Comment by JoshuaNitschke** [comment]
Confirming I do have my  .npmrc currently set to 

`legacy-peer-deps=true`

(But I think I did that for a different dependency, not kinde, but I can't remember)

**Comment by luukhaijes** [comment]
Thanks for creating this issue, if you're able to provide a PR for this it would be great. Currently I'm unable to do so, just bought a house and started rebuilding it. If you're unable to provide PR I can try to work on it in between.

**Comment by luukhaijes** [comment]
I'm back, I can have a look at it this week±

**Comment by luukhaijes** [comment]
Hi, sorry for the late response. Still working on my house renovations, found some time to work on this. Hope to have a PR ready by tomorrow.

**Comment by luukhaijes** [comment]
I have a PR, sorry for the delay.
