### ISSUE TITLE
Add featureFlag directive

### ISSUE THREAD

**Issue by luukhaijes** [luukhaijes/kinde-angular#7]
### As a:
Developer

### I want:
- To be able to conditionally render UI elements based on the state of a feature flag
- To achieve this in a declarative and maintainable way within my templates

### So that:
- I can easily control the rollout of new features to specific user groups or environments
- I can experiment with different UI variations without affecting the entire user base
- I can keep my component logic clean and focused on core functionality

### Acceptance Criteria:
- A new directive named ``featureFlag`` is created.
- The directive accepts the name of a feature flag as an input.
- The directive conditionally renders its content based on the value of the specified feature flag.
- The directive supports both boolean and string-based feature flag values.
- The directive provides an optional alternative template to display when the feature flag is disabled.
- The directive integrates seamlessly with existing feature flag management solutions.
- Unit tests are written to ensure the functionality of the directive.
 
### Additional Considerations:
- Explore the possibility of supporting different comparison operators (e.g., equal to, not equal to) for feature flag values.
- Consider providing mechanisms for handling scenarios where the feature flag value is unknown or unavailable.
- Ensure the directive is performant and does not introduce significant overhead to the application.

**Comment by domvanrob** [comment]
Hey @luukhaijes!

Was wondering whether this feature will still be developed, and if so, if there's a rough ETA on when this going to be released. The current implementation of the guards is great, but without the directive for UI manipulation, also quite redundant, as you'll still need to implement this yourself. 

Would be a great addition and get more Angular developers to try out Kinde!

**Comment by luukhaijes** [comment]
Hey @domvanrob,

This feature is still on my mind, lately I have been busy buying a house with my girlfriend so I was a bit preoccupied. You're totally correct that this makes sense to have this with the guard. I will make an optimistic ETA of 2 weeks, I'm also going away for three days so after that I will dive into this and will ping you when I'm ready.

**Comment by luukhaijes** [comment]
Hey @domvanrob, working on it as we speak. Will be done somewhere coming firday.

**Comment by luukhaijes** [comment]
Fixed by #14
